<?php

return [[ 'text' => 'English/Welsh/scottish/Northern Irish/British', 'value' => 31],
    [ 'text' => 'Irish', 'value' => 32],
    [ 'text' => 'Gypsy or Irish Traveller', 'value' => 33],
    [ 'text' => 'Any other white background', 'value' => 34],
    [ 'text' => 'White and black Caribbean', 'value' => 35],
    [ 'text' => 'White and black African', 'value' => 36],
    [ 'text' => 'White and Asian', 'value' => 37],
    [ 'text' => 'Any other mixed/multiple ethnic background', 'value' => 38],
    [ 'text' => 'Indian', 'value' => 39],
    [ 'text' => 'Pakistani', 'value' => 40],
    [ 'text' => 'Bangladeshi', 'value' => 41],
    [ 'text' => 'Chinese', 'value' => 42],
    [ 'text' => 'Any other Asian background', 'value' => 43],
    [ 'text' => 'African', 'value' => 44],
    [ 'text' => 'Caribbean', 'value' => 45],
    [ 'text' => 'Any other Black/African/Carribean background', 'value' => 46],
    [ 'text' => 'Arab', 'value' => 47],
    [ 'text' => 'Any other ethnic group', 'value' => 98],
    [ 'text' => 'Don\'t know', 'value' => 99]];
