<?php

return [[ 'text' => 'Senior Care Worker', 'value' => 7],
    [ 'text' => 'Care Worker', 'value' => 8],
    [ 'text' => 'Community Support and Outreach Work', 'value' => 9],
    [ 'text' => 'Advice Guidance and Advocacy', 'value' => 11],
    [ 'text' => 'Other care-providing job role', 'value' => 23],
    [ 'text' => 'Senior Management', 'value' => 1],
    [ 'text' => 'Middle Management', 'value' => 2],
    [ 'text' => 'First Line Manager', 'value' => 3],
    [ 'text' => 'Registered Manager', 'value' => 4],
    [ 'text' => 'Supervisor', 'value' => 5],
    [ 'text' => 'Managers and staff in care-related but not care-providing roles', 'value' => 24],
    [ 'text' => 'Social Worker', 'value' => 6],
    [ 'text' => 'Occupational Therapist', 'value' => 15],
    [ 'text' => 'Registered Nurse', 'value' => 16],
    [ 'text' => 'Allied Health Professional', 'value' => 17],
    [ 'text' => 'Safeguarding and reviewing officer', 'value' => 35],
    [ 'text' => 'Administrative or office staff not care-providing', 'value' => 25],
    [ 'text' => 'Ancillary staff not care-providing', 'value' => 26],
    [ 'text' => 'Activities worker or co-ordinator', 'value' => 34],
    [ 'text' => 'Occupational therapist assistant', 'value' => 36],
    [ 'text' => 'Other non-care-providing job roles', 'value' => 27]];