<?php

return [[ 'text' => 'Afghanistan', 'value' => 4],
    [ 'text' => 'Aland Islands', 'value' => 248],
    [ 'text' => 'Albania', 'value' => 8],
    [ 'text' => 'Algeria', 'value' => 12],
    [ 'text' => 'American Samoa', 'value' => 16],
    [ 'text' => 'Andorra', 'value' => 20],
    [ 'text' => 'Angola', 'value' => 24],
    [ 'text' => 'Anguilla', 'value' => 660],
    [ 'text' => 'Antarctica', 'value' => 10],
    [ 'text' => 'Antigua and Barbuda', 'value' => 28],
    [ 'text' => 'Argentina', 'value' => 32],
    [ 'text' => 'Armenia', 'value' => 51],
    [ 'text' => 'Aruba', 'value' => 533],
    [ 'text' => 'Australia', 'value' => 36],
    [ 'text' => 'Austria', 'value' => 40],
    [ 'text' => 'Azerbaijan', 'value' => 31],
    [ 'text' => 'Bahamas', 'value' => 44],
    [ 'text' => 'Bahrain', 'value' => 48],
    [ 'text' => 'Bangladesh', 'value' => 50],
    [ 'text' => 'Barbados', 'value' => 52],
    [ 'text' => 'Belarus', 'value' => 112],
    [ 'text' => 'Belgium', 'value' => 56],
    [ 'text' => 'Belize', 'value' => 84],
    [ 'text' => 'Benin', 'value' => 204],
    [ 'text' => 'Bermuda', 'value' => 60],
    [ 'text' => 'Bhutan', 'value' => 64],
    [ 'text' => 'Bolivia', 'value' => 68],
    [ 'text' => 'Bosnia and Herzegovina', 'value' => 70],
    [ 'text' => 'Botswana', 'value' => 72],
    [ 'text' => 'Bouvet Island', 'value' => 74],
    [ 'text' => 'Brazil', 'value' => 76],
    [ 'text' => 'British Indian Ocean Territory', 'value' => 86],
    [ 'text' => 'Brunei Darussalam', 'value' => 96],
    [ 'text' => 'Bulgaria', 'value' => 100],
    [ 'text' => 'Burkina Faso', 'value' => 854],
    [ 'text' => 'Burundi', 'value' => 108],
    [ 'text' => 'Cambodia', 'value' => 116],
    [ 'text' => 'Cameroon', 'value' => 120],
    [ 'text' => 'Canada', 'value' => 124],
    [ 'text' => 'Cape Verde', 'value' => 132],
    [ 'text' => 'Cayman Islands', 'value' => 136],
    [ 'text' => 'Central African Republic', 'value' => 140],
    [ 'text' => 'Chad', 'value' => 148],
    [ 'text' => 'Chile', 'value' => 152],
    [ 'text' => 'China', 'value' => 156],
    [ 'text' => 'Christmas Island', 'value' => 162],
    [ 'text' => 'Cocos (Keeling) Islands', 'value' => 166],
    [ 'text' => 'Colombia', 'value' => 170],
    [ 'text' => 'Comoros', 'value' => 174],
    [ 'text' => 'Congo', 'value' => 178],
    [ 'text' => 'Congo Democratic Republic of the', 'value' => 180],
    [ 'text' => 'Cook Islands', 'value' => 184],
    [ 'text' => 'Costa Rica', 'value' => 188],
    [ 'text' => 'Cote d\'Ivoire', 'value' => 384],
[ 'text' => 'Croatia', 'value' => 191],
[ 'text' => 'Cuba', 'value' => 192],
[ 'text' => 'Cyprus', 'value' => 196],
[ 'text' => 'Czech Republic', 'value' => 203],
[ 'text' => 'Denmark', 'value' => 208],
[ 'text' => 'Djibouti', 'value' => 262],
[ 'text' => 'Dominica', 'value' => 212],
[ 'text' => 'Dominican Republic', 'value' => 214],
[ 'text' => 'Ecuador', 'value' => 218],
[ 'text' => 'Egypt', 'value' => 818],
[ 'text' => 'El Salvador', 'value' => 222],
[ 'text' => 'Equatorial Guinea', 'value' => 226],
[ 'text' => 'Eritrea', 'value' => 232],
[ 'text' => 'Estonia', 'value' => 233],
[ 'text' => 'Ethiopia', 'value' => 231],
[ 'text' => 'Falkland Islands (Malvinas)', 'value' => 238],
[ 'text' => 'Faroe Islands', 'value' => 234],
[ 'text' => 'Fiji', 'value' => 242],
[ 'text' => 'Finland', 'value' => 246],
[ 'text' => 'France', 'value' => 250],
[ 'text' => 'French Guiana', 'value' => 254],
[ 'text' => 'French Polynesia', 'value' => 258],
[ 'text' => 'French Southern Territories', 'value' => 260],
[ 'text' => 'Gabon', 'value' => 266],
[ 'text' => 'Gambia', 'value' => 270],
[ 'text' => 'Georgia', 'value' => 268],
[ 'text' => 'Germany', 'value' => 276],
[ 'text' => 'Ghana', 'value' => 288],
[ 'text' => 'Gibraltar', 'value' => 292],
[ 'text' => 'Greece', 'value' => 300],
[ 'text' => 'Greenland', 'value' => 304],
[ 'text' => 'Grenada', 'value' => 308],
[ 'text' => 'Guadeloupe', 'value' => 312],
[ 'text' => 'Guam', 'value' => 316],
[ 'text' => 'Guatemala', 'value' => 320],
[ 'text' => 'Guernsey', 'value' => 831],
[ 'text' => 'Guinea', 'value' => 324],
[ 'text' => 'Guinea-Bissau', 'value' => 624],
[ 'text' => 'Guyana', 'value' => 328],
[ 'text' => 'Haiti', 'value' => 332],
[ 'text' => 'Gibraltar', 'value' => 292],
[ 'text' => 'Greece', 'value' => 300],
[ 'text' => 'Greenland', 'value' => 304],
[ 'text' => 'Grenada', 'value' => 308],
[ 'text' => 'Guadeloupe', 'value' => 312],
[ 'text' => 'Guam', 'value' => 316],
[ 'text' => 'Guatemala', 'value' => 320],
[ 'text' => 'Guernsey', 'value' => 831],
[ 'text' => 'Guinea', 'value' => 324],
[ 'text' => 'Guinea-Bissau', 'value' => 624],
[ 'text' => 'Guyana', 'value' => 328],
[ 'text' => 'Haiti', 'value' => 332],
[ 'text' => 'Heard Island and McDonald Islands', 'value' => 334],
[ 'text' => 'Holy See (Vatican City State)', 'value' => 336],
[ 'text' => 'Honduras', 'value' => 340],
[ 'text' => 'Hong Kong', 'value' => 344],
[ 'text' => 'Hungary', 'value' => 348],
[ 'text' => 'Iceland', 'value' => 352],
[ 'text' => 'India', 'value' => 356],
[ 'text' => 'Indonesia', 'value' => 360],
[ 'text' => 'Iran Islamic Republic of', 'value' => 364],
[ 'text' => 'Iraq', 'value' => 368],
[ 'text' => 'Ireland', 'value' => 372],
[ 'text' => 'Israel', 'value' => 376],
[ 'text' => 'Italy', 'value' => 380],
[ 'text' => 'Jamaica', 'value' => 388],
[ 'text' => 'Japan', 'value' => 392],
[ 'text' => 'Jersey', 'value' => 832],
[ 'text' => 'Jordan', 'value' => 400],
[ 'text' => 'Kazakhstan', 'value' => 398],
[ 'text' => 'Kenya', 'value' => 404],
[ 'text' => 'Kiribati', 'value' => 296],
[ 'text' => 'Korea Democratic People\'s Republic of', 'value' => 408],
[ 'text' => 'Korea Republic of', 'value' => 410],
[ 'text' => 'Kuwait', 'value' => 414],
[ 'text' => 'Kyrgyzstan', 'value' => 417],
[ 'text' => 'Latvia', 'value' => 428],
[ 'text' => 'Lebanon', 'value' => 422],
[ 'text' => 'Lesotho', 'value' => 426],
[ 'text' => 'Liberia', 'value' => 430],
[ 'text' => 'Libyan Arab Jamahiriya', 'value' => 434],
[ 'text' => 'Liechtenstein', 'value' => 438],
[ 'text' => 'Lithuania', 'value' => 440],
[ 'text' => 'Luxembourg', 'value' => 442],
[ 'text' => 'Macao', 'value' => 446],
[ 'text' => 'Macedonia the former Yugoslav Republic of', 'value' => 807],
[ 'text' => 'Madagascar', 'value' => 450],
[ 'text' => 'Malawi', 'value' => 454],
[ 'text' => 'Malaysia', 'value' => 458],
[ 'text' => 'Maldives', 'value' => 462],
[ 'text' => 'Mali', 'value' => 466],
[ 'text' => 'Malta', 'value' => 470],
[ 'text' => 'Marshall Islands', 'value' => 584],
[ 'text' => 'Martinique', 'value' => 474],
[ 'text' => 'Mauritania', 'value' => 478],
[ 'text' => 'Mauritius', 'value' => 480],
[ 'text' => 'Mayotte', 'value' => 175],
[ 'text' => 'Mexico', 'value' => 484],
[ 'text' => 'Micronesia Federated States of', 'value' => 583],
[ 'text' => 'Moldova', 'value' => 498],
[ 'text' => 'Monaco', 'value' => 492],
[ 'text' => 'Mongolia', 'value' => 496],
[ 'text' => 'Montenegro', 'value' => 499],
[ 'text' => 'Montserrat', 'value' => 500],
[ 'text' => 'Morocco', 'value' => 504],
[ 'text' => 'Mozambique', 'value' => 508],
[ 'text' => 'Myanmar', 'value' => 104],
[ 'text' => 'Namibia', 'value' => 516],
[ 'text' => 'Nauru', 'value' => 520],
[ 'text' => 'Nepal', 'value' => 524],
[ 'text' => 'Netherlands', 'value' => 528],
[ 'text' => 'Netherlands Antilles', 'value' => 530],
[ 'text' => 'New Caledonia', 'value' => 540],
[ 'text' => 'New Zealand', 'value' => 554],
[ 'text' => 'Nicaragua', 'value' => 558],
[ 'text' => 'Niger', 'value' => 562],
[ 'text' => 'Nigeria', 'value' => 566],
[ 'text' => 'Niue', 'value' => 570],
[ 'text' => 'Norfolk Island', 'value' => 574],
[ 'text' => 'Northern Mariana Islands', 'value' => 580],
[ 'text' => 'Norway', 'value' => 578],
[ 'text' => 'Oman', 'value' => 512],
[ 'text' => 'Pakistan', 'value' => 586],
[ 'text' => 'Palau', 'value' => 585],
[ 'text' => 'Palestinian Territory Occupied', 'value' => 275],
[ 'text' => 'Panama', 'value' => 591],
[ 'text' => 'Papua New Guinea', 'value' => 598],
[ 'text' => 'Paraguay', 'value' => 600],
[ 'text' => 'Peru', 'value' => 604],
[ 'text' => 'Philippines', 'value' => 608],
[ 'text' => 'Pitcairn', 'value' => 612],
[ 'text' => 'Poland', 'value' => 616],
[ 'text' => 'Portugal', 'value' => 620],
[ 'text' => 'Puerto Rico', 'value' => 630],
[ 'text' => 'Qatar', 'value' => 634],
[ 'text' => 'Reunion', 'value' => 638],
[ 'text' => 'Romania', 'value' => 642],
[ 'text' => 'Russian Federation', 'value' => 643],
[ 'text' => 'Rwanda', 'value' => 646],
[ 'text' => 'Saint Barthelemy', 'value' => 652],
[ 'text' => 'Saint Helena', 'value' => 654],
[ 'text' => 'Saint Kitts and Nevis', 'value' => 659],
[ 'text' => 'Saint Lucia', 'value' => 662],
[ 'text' => 'Saint Martin (French part)', 'value' => 663],
[ 'text' => 'Saint Pierre and Miquelon', 'value' => 666],
[ 'text' => 'Saint Vincent and the Grenadines', 'value' => 670],
[ 'text' => 'Samoa', 'value' => 882],
[ 'text' => 'San Marino', 'value' => 674],
[ 'text' => 'Sao Tome and Principe', 'value' => 678],
[ 'text' => 'Saudi Arabia', 'value' => 682],
[ 'text' => 'Senegal', 'value' => 686],
[ 'text' => 'Serbia', 'value' => 688],
[ 'text' => 'Seychelles', 'value' => 690],
[ 'text' => 'Sierra Leone', 'value' => 694],
[ 'text' => 'Singapore', 'value' => 702],
[ 'text' => 'Slovakia', 'value' => 703],
[ 'text' => 'Slovenia', 'value' => 705],
[ 'text' => 'Solomon Islands', 'value' => 90],
[ 'text' => 'Somalia', 'value' => 706],
[ 'text' => 'South Africa', 'value' => 710],
[ 'text' => 'South Georgia and the South Sandwich Islands', 'value' => 239],
[ 'text' => 'South Sudan', 'value' => 728],
[ 'text' => 'Spain', 'value' => 724],
[ 'text' => 'Sri Lanka', 'value' => 144],
[ 'text' => 'Sudan', 'value' => 736],
[ 'text' => 'Suriname', 'value' => 740],
[ 'text' => 'Svalbard and Jan Mayen', 'value' => 744],
[ 'text' => 'Swaziland', 'value' => 748],
[ 'text' => 'Sweden', 'value' => 752],
[ 'text' => 'Switzerland', 'value' => 756],
[ 'text' => 'Syrian Arab Republic', 'value' => 760],
[ 'text' => 'Taiwan Province of China', 'value' => 158],
[ 'text' => 'Tajikistan', 'value' => 762],
[ 'text' => 'Tanzania United Republic of', 'value' => 834],
[ 'text' => 'Thailand', 'value' => 764],
[ 'text' => 'Timor-Leste', 'value' => 626],
[ 'text' => 'Togo', 'value' => 768],
[ 'text' => 'Tokelau', 'value' => 772],
[ 'text' => 'Tonga', 'value' => 776],
[ 'text' => 'Trinidad and Tobago', 'value' => 780],
[ 'text' => 'Tunisia', 'value' => 788],
[ 'text' => 'Turkey', 'value' => 792],
[ 'text' => 'Turkmenistan', 'value' => 795],
[ 'text' => 'Turks and Caicos Islands', 'value' => 796],
[ 'text' => 'Tuvalu', 'value' => 798],
[ 'text' => 'Uganda', 'value' => 800],
[ 'text' => 'Ukraine', 'value' => 804],
[ 'text' => 'United Arab Emirates', 'value' => 784],
[ 'text' => 'United States', 'value' => 840],
[ 'text' => 'United States Minor Outlying Islands', 'value' => 581],
[ 'text' => 'Uruguay', 'value' => 858],
[ 'text' => 'Uzbekistan', 'value' => 860],
[ 'text' => 'Vanuatu', 'value' => 548],
[ 'text' => 'Venezuela', 'value' => 862],
[ 'text' => 'Viet Nam', 'value' => 704],
[ 'text' => 'Virgin Islands British', 'value' => 92],
[ 'text' => 'Virgin Islands U.S.', 'value' => 850],
[ 'text' => 'Wallis and Futuna', 'value' => 876],
[ 'text' => 'Western Sahara', 'value' => 732],
[ 'text' => 'Yemen', 'value' => 887],
[ 'text' => 'Zambia', 'value' => 894],
[ 'text' => 'Zimbabwe', 'value' => 716],
[ 'text' => 'Don\'t know', 'value' => 999]];
